/* The following code was generated by JFlex 1.4.3 on 1/23/16 2:45 PM */

 /***************************/
/* FILE NAME: LEX_FILE.lex */
/***************************/

/***************************/
/* AUTHOR: OREN ISH SHALOM */
/***************************/

/*************/
/* USER CODE */ 
/*************/
   
import java_cup.runtime.*;
 
/******************************/
/* DOLAR DOLAR - DON'T TOUCH! */
/******************************/
      

class IRLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\12\1\2\1\0\1\12\1\1\22\0\1\13\1\7\1\4"+
    "\1\14\4\7\1\63\1\64\2\7\1\62\1\7\1\66\1\7\12\15"+
    "\1\17\2\7\1\65\3\7\1\24\1\15\1\50\1\42\1\57\1\30"+
    "\1\56\1\15\1\43\1\53\1\15\1\34\1\20\1\45\1\46\2\15"+
    "\1\61\1\37\1\54\1\15\1\60\1\15\1\47\2\15\1\10\1\3"+
    "\1\11\1\7\1\16\1\7\1\26\1\41\1\44\1\33\1\23\1\15"+
    "\1\35\1\36\1\31\2\15\1\32\1\51\1\6\1\21\1\52\1\15"+
    "\1\25\1\55\1\5\1\40\1\22\2\15\1\27\1\15\4\7\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\15\3\1\11\1\12\1\13\1\14\1\15"+
    "\1\0\1\16\1\0\1\3\2\6\16\3\1\17\5\3"+
    "\1\20\1\21\1\3\1\22\1\23\1\24\1\3\1\25"+
    "\2\3\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\4\3\1\35\1\0\1\36\4\3\1\37\11\3\1\40"+
    "\1\3\1\41\11\3\1\42\1\3\1\43\1\3\1\44"+
    "\3\3\1\45\1\3\1\46\10\3\1\47\1\3\1\50"+
    "\1\51\2\3\1\52\2\3\1\53\1\3\1\54\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\67\0\245\0\334\0\67\0\67"+
    "\0\u0113\0\u014a\0\67\0\u0181\0\u01b8\0\u01ef\0\u0226\0\u025d"+
    "\0\u0294\0\u02cb\0\u0302\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415"+
    "\0\67\0\67\0\67\0\67\0\67\0\u044c\0\67\0\245"+
    "\0\u0483\0\u04ba\0\67\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd"+
    "\0\u0604\0\u063b\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e\0\u0785"+
    "\0\u07bc\0\u0483\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf\0\67"+
    "\0\u0906\0\u093d\0\u0483\0\u0483\0\u0483\0\u0974\0\u0483\0\u09ab"+
    "\0\u09e2\0\u0483\0\u0483\0\u0483\0\u0483\0\u0483\0\u0483\0\u0483"+
    "\0\u0a19\0\u0a50\0\u0a87\0\u0abe\0\67\0\u0906\0\u0af5\0\u0b2c"+
    "\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4"+
    "\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c"+
    "\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\u0fe6\0\u101d\0\u1054"+
    "\0\u108b\0\u0483\0\u10c2\0\u0483\0\u10f9\0\u0483\0\u1130\0\u1167"+
    "\0\u119e\0\u0483\0\u11d5\0\u0483\0\u120c\0\u1243\0\u127a\0\u12b1"+
    "\0\u12e8\0\u131f\0\u1356\0\u138d\0\u0483\0\u13c4\0\u0483\0\u0483"+
    "\0\u13fb\0\u1432\0\u0483\0\u1469\0\u14a0\0\u0483\0\u14d7\0\u0483"+
    "\0\u0483";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\2\6\1\2\1\7"+
    "\1\10\2\4\1\11\1\6\1\12\1\13\1\14\3\6"+
    "\1\15\7\6\1\16\2\6\1\17\2\6\1\20\1\21"+
    "\1\6\1\22\1\23\1\24\1\25\2\6\1\26\4\6"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\71\0"+
    "\1\4\67\0\1\36\1\37\5\40\1\0\54\40\5\0"+
    "\2\41\6\0\2\41\1\0\42\41\5\0\1\11\1\42"+
    "\1\43\64\11\5\0\2\44\6\0\2\44\1\0\42\44"+
    "\12\0\2\41\6\0\2\41\1\0\1\41\1\45\16\41"+
    "\1\46\21\41\12\0\1\41\1\47\6\0\2\41\1\0"+
    "\5\41\1\50\5\41\1\51\26\41\12\0\2\41\6\0"+
    "\2\41\1\0\11\41\1\52\30\41\12\0\1\53\1\41"+
    "\6\0\2\41\1\0\20\41\1\54\21\41\12\0\2\41"+
    "\6\0\2\41\1\0\3\41\1\55\5\41\1\56\30\41"+
    "\12\0\1\41\1\57\6\0\2\41\1\0\42\41\12\0"+
    "\2\41\6\0\2\41\1\0\1\41\1\60\1\41\1\61"+
    "\36\41\12\0\2\41\6\0\2\41\1\0\5\41\1\62"+
    "\34\41\12\0\2\41\6\0\2\41\1\0\1\41\1\63"+
    "\40\41\12\0\2\41\6\0\2\41\1\0\1\41\1\64"+
    "\40\41\12\0\2\41\6\0\2\41\1\0\20\41\1\65"+
    "\21\41\12\0\2\41\6\0\2\41\1\0\11\41\1\66"+
    "\30\41\12\0\2\41\6\0\2\41\1\0\3\41\1\67"+
    "\36\41\10\0\4\40\65\0\2\41\6\0\2\41\1\70"+
    "\42\41\7\0\1\43\71\0\2\44\6\0\2\44\1\71"+
    "\42\44\12\0\2\41\6\0\2\41\1\70\2\41\1\72"+
    "\10\41\1\73\26\41\12\0\2\41\6\0\2\41\1\70"+
    "\12\41\1\74\27\41\12\0\2\41\6\0\2\41\1\70"+
    "\13\41\1\75\26\41\12\0\2\41\6\0\2\41\1\70"+
    "\5\41\1\76\34\41\12\0\2\41\6\0\2\41\1\70"+
    "\13\41\1\77\26\41\12\0\2\41\6\0\2\41\1\70"+
    "\21\41\1\100\20\41\12\0\2\41\6\0\2\41\1\70"+
    "\6\41\1\101\33\41\12\0\2\41\6\0\2\41\1\70"+
    "\21\41\1\102\20\41\12\0\2\41\6\0\2\41\1\70"+
    "\24\41\1\103\15\41\12\0\2\41\6\0\2\41\1\70"+
    "\2\41\1\104\37\41\12\0\2\41\6\0\2\41\1\70"+
    "\24\41\1\105\15\41\12\0\1\106\1\41\6\0\2\41"+
    "\1\70\42\41\12\0\2\41\6\0\2\41\1\70\15\41"+
    "\1\107\24\41\12\0\2\41\6\0\2\41\1\70\5\41"+
    "\1\110\34\41\12\0\2\41\6\0\2\41\1\70\31\41"+
    "\1\111\10\41\12\0\2\41\6\0\2\41\1\70\31\41"+
    "\1\112\10\41\12\0\2\41\6\0\2\41\1\70\5\41"+
    "\1\113\34\41\12\0\1\114\1\41\6\0\2\41\1\70"+
    "\42\41\15\0\1\115\1\0\2\116\60\0\2\41\6\0"+
    "\2\41\1\70\3\41\1\117\36\41\12\0\2\41\6\0"+
    "\2\41\1\70\6\41\1\120\33\41\12\0\2\41\6\0"+
    "\2\41\1\70\5\41\1\121\34\41\12\0\1\122\1\41"+
    "\6\0\2\41\1\70\42\41\12\0\2\41\6\0\2\41"+
    "\1\70\32\41\1\123\7\41\12\0\2\41\6\0\2\41"+
    "\1\70\32\41\1\124\7\41\12\0\1\125\1\41\6\0"+
    "\2\41\1\70\42\41\12\0\2\41\6\0\2\41\1\70"+
    "\20\41\1\126\21\41\12\0\2\41\6\0\2\41\1\70"+
    "\4\41\1\127\3\41\1\130\31\41\12\0\2\41\6\0"+
    "\2\41\1\70\7\41\1\131\32\41\12\0\2\41\6\0"+
    "\2\41\1\70\6\41\1\132\33\41\12\0\2\41\6\0"+
    "\2\41\1\70\11\41\1\133\30\41\12\0\2\41\6\0"+
    "\2\41\1\70\6\41\1\134\33\41\12\0\2\41\6\0"+
    "\2\41\1\70\10\41\1\135\3\41\1\136\17\41\1\137"+
    "\1\41\1\140\3\41\12\0\2\41\6\0\2\41\1\70"+
    "\20\41\1\141\21\41\12\0\2\41\6\0\2\41\1\70"+
    "\5\41\1\142\34\41\12\0\2\41\6\0\2\41\1\70"+
    "\5\41\1\143\34\41\12\0\2\41\6\0\2\41\1\70"+
    "\11\41\1\144\30\41\12\0\2\41\6\0\2\41\1\70"+
    "\14\41\1\145\25\41\12\0\2\41\6\0\2\41\1\70"+
    "\5\41\1\146\34\41\12\0\2\41\6\0\2\41\1\70"+
    "\24\41\1\147\15\41\12\0\2\41\6\0\2\41\1\70"+
    "\5\41\1\150\34\41\12\0\2\41\6\0\2\41\1\70"+
    "\6\41\1\151\33\41\12\0\2\41\6\0\2\41\1\70"+
    "\37\41\1\152\2\41\12\0\2\41\6\0\2\41\1\70"+
    "\5\41\1\153\34\41\12\0\2\41\6\0\2\41\1\70"+
    "\37\41\1\154\2\41\12\0\2\41\6\0\2\41\1\70"+
    "\6\41\1\155\33\41\12\0\1\41\1\156\6\0\2\41"+
    "\1\70\42\41\12\0\2\41\6\0\2\41\1\70\5\41"+
    "\1\157\34\41\12\0\2\41\6\0\2\41\1\70\3\41"+
    "\1\160\36\41\12\0\2\41\6\0\2\41\1\70\3\41"+
    "\1\161\36\41\12\0\2\41\6\0\2\41\1\70\7\41"+
    "\1\162\32\41\12\0\2\41\6\0\2\41\1\70\30\41"+
    "\1\163\11\41\12\0\2\41\6\0\2\41\1\70\3\41"+
    "\1\164\36\41\12\0\2\41\6\0\2\41\1\70\12\41"+
    "\1\165\27\41\12\0\2\41\6\0\2\41\1\70\20\41"+
    "\1\166\21\41\12\0\2\41\6\0\2\41\1\70\12\41"+
    "\1\167\27\41\12\0\2\41\6\0\2\41\1\70\6\41"+
    "\1\170\33\41\12\0\2\41\6\0\2\41\1\70\12\41"+
    "\1\171\27\41\12\0\1\41\1\172\6\0\2\41\1\70"+
    "\42\41\12\0\2\41\6\0\2\41\1\70\6\41\1\173"+
    "\33\41\12\0\2\41\6\0\2\41\1\70\35\41\1\174"+
    "\4\41\12\0\2\41\6\0\2\41\1\70\3\41\1\175"+
    "\36\41\12\0\2\41\6\0\2\41\1\70\30\41\1\176"+
    "\11\41\12\0\2\41\6\0\2\41\1\70\7\41\1\177"+
    "\32\41\12\0\2\41\6\0\2\41\1\70\13\41\1\200"+
    "\26\41\12\0\2\41\6\0\2\41\1\70\15\41\1\201"+
    "\24\41\12\0\2\41\6\0\2\41\1\70\12\41\1\202"+
    "\27\41\12\0\2\41\6\0\2\41\1\70\3\41\1\203"+
    "\36\41\12\0\2\41\6\0\2\41\1\70\6\41\1\204"+
    "\33\41\12\0\1\205\1\41\6\0\2\41\1\70\42\41"+
    "\12\0\2\41\6\0\2\41\1\70\12\41\1\206\27\41"+
    "\12\0\2\41\6\0\2\41\1\70\12\41\1\207\27\41"+
    "\12\0\2\41\6\0\2\41\1\70\16\41\1\210\23\41"+
    "\12\0\2\41\6\0\2\41\1\70\12\41\1\211\27\41"+
    "\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5390];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\2\1\2\11\2\1\1\11"+
    "\15\1\5\11\1\0\1\11\1\0\2\1\1\11\24\1"+
    "\1\11\24\1\1\11\1\0\73\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public void printLineNumber(){
	System.out.println();
	System.out.print(yyline+1);
	System.out.print(": "); 
}  

public int getLineNumber(){
	return yyline+1;
} 

private Token printToken(String token_name, int token_sym) {
	/*printLineNumber(); 
	System.out.print(token_name); */
	return symbol(token_sym, token_name);
}

private Token printToken(String token_name, int token_sym, Object value) {
	/*printLineNumber(); 
	System.out.print(token_name); */
	return symbol(token_sym, token_name, value);
}
    
 
/*************************************************************************

********/
    /* Create a new java_cup.runtime.Symbol with information about the 

current token */
    

/*************************************************************************
 
********/
    private Token symbol(int type, String token_name)               
   		{return new Token(type, yyline, yycolumn, token_name);}
    private Token symbol(int type, String token_name, Object value) 
    	{return new Token(type, yyline, yycolumn, token_name, value);}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  IRLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  IRLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 160) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 31: 
          { return printToken("Jump",IRsym.JUMP);
          }
        case 46: break;
        case 28: 
          { return printToken("Xor",IRsym.XOR);
          }
        case 47: break;
        case 29: 
          { return printToken(new String(yytext()),	IRsym.DVLABEL);
          }
        case 48: break;
        case 39: 
          { return printToken("JumpTrue",IRsym.JUMPTRUE);
          }
        case 49: break;
        case 38: 
          { return printToken("Compare",IRsym.COMPARE);
          }
        case 50: break;
        case 12: 
          { return printToken("ASSIGN", IRsym.ASSIGN);
          }
        case 51: break;
        case 16: 
          { return printToken(new String(yytext()), IRsym.STRINGLABEL);
          }
        case 52: break;
        case 27: 
          { return printToken("Neg",IRsym.NEG);
          }
        case 53: break;
        case 33: 
          { return printToken("JumpG",IRsym.JUMPG);
          }
        case 54: break;
        case 14: 
          { return printToken(new String(yytext()), IRsym.QUOTE);
          }
        case 55: break;
        case 7: 
          { return printToken("_",IRsym.UNDER);
          }
        case 56: break;
        case 2: 
          { /* just skip what was found, do nothing */
          }
        case 57: break;
        case 5: 
          { return printToken("RB",IRsym.RB);
          }
        case 58: break;
        case 1: 
          { throw new RuntimeException("Error: Invalid token: "+new String(yytext())+" at line " +Integer.toString(yyline+1));
          }
        case 59: break;
        case 6: 
          { return printToken(new String(yytext()), IRsym.COMMENT);
          }
        case 60: break;
        case 44: 
          { return printToken("ArrayLength",IRsym.ARRAYLENGTH);
          }
        case 61: break;
        case 45: 
          { return printToken("VirtualCall",IRsym.VIRTUALCALL);
          }
        case 62: break;
        case 26: 
          { return printToken("Not",IRsym.NOT);
          }
        case 63: break;
        case 21: 
          { return printToken("Add",IRsym.ADD);
          }
        case 64: break;
        case 40: 
          { return printToken("MoveArray", IRsym.MOVEARRAY);
          }
        case 65: break;
        case 32: 
          { return printToken("JumpL",IRsym.JUMPL);
          }
        case 66: break;
        case 37: 
          { return printToken("Library",IRsym.LIBRARY);
          }
        case 67: break;
        case 35: 
          { return printToken("JumpGE",IRsym.JUMPGE);
          }
        case 68: break;
        case 4: 
          { return printToken("LB",IRsym.LB);
          }
        case 69: break;
        case 11: 
          { return printToken("RP",IRsym.RP);
          }
        case 70: break;
        case 42: 
          { return printToken("JumpFalse",IRsym.JUMPFALSE);
          }
        case 71: break;
        case 25: 
          { return printToken("Inc",IRsym.INC);
          }
        case 72: break;
        case 9: 
          { return printToken(",",IRsym.COMMA);
          }
        case 73: break;
        case 8: 
          { return printToken(":",IRsym.COLON);
          }
        case 74: break;
        case 13: 
          { return printToken("DOT",IRsym.DOT);
          }
        case 75: break;
        case 24: 
          { return printToken("Div",IRsym.DIV);
          }
        case 76: break;
        case 41: 
          { return printToken("MoveField",IRsym.MOVEFIELD);
          }
        case 77: break;
        case 20: 
          { return printToken("And",IRsym.AND);
          }
        case 78: break;
        case 15: 
          { return printToken("Or",IRsym.OR);
          }
        case 79: break;
        case 10: 
          { return printToken("LP",IRsym.LP);
          }
        case 80: break;
        case 34: 
          { return printToken("JumpLE",IRsym.JUMPLE);
          }
        case 81: break;
        case 36: 
          { return printToken("Return",IRsym.RETURN);
          }
        case 82: break;
        case 17: 
          { return printToken(new String(yytext()),	IRsym.LABEL);
          }
        case 83: break;
        case 43: 
          { return printToken("StaticCall",IRsym.STATICCALL);
          }
        case 84: break;
        case 23: 
          { return printToken("Dec",IRsym.DEC);
          }
        case 85: break;
        case 18: 
          { return printToken("Mod",IRsym.MOD);
          }
        case 86: break;
        case 30: 
          { return printToken("Move", IRsym.MOVE);
          }
        case 87: break;
        case 22: 
          { return printToken("Sub",IRsym.SUB);
          }
        case 88: break;
        case 19: 
          { return printToken("Mul",IRsym.MUL);
          }
        case 89: break;
        case 3: 
          { return printToken(new String(yytext()), IRsym.WORD);
          }
        case 90: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return printToken("EOF", IRsym.EOF, new String(yytext()));
            }
            case 138: break;
            default:
              { return new java_cup.runtime.Symbol(sym.EOF); }
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
