
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 03 18:20:03 IST 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LCBR = 26;
  public static final int LTE = 32;
  public static final int INTEGER = 51;
  public static final int SEMI = 42;
  public static final int LPAREN = 6;
  public static final int CONTINUE = 13;
  public static final int INT = 22;
  public static final int MINUS = 33;
  public static final int STATIC = 43;
  public static final int RPAREN = 7;
  public static final int SEMICOLON = 2;
  public static final int LT = 31;
  public static final int LP = 25;
  public static final int COMMA = 12;
  public static final int CLASS = 11;
  public static final int RP = 41;
  public static final int MULTIPLY = 35;
  public static final int PLUS = 3;
  public static final int QUOTE = 53;
  public static final int ASSIGN = 8;
  public static final int IF = 21;
  public static final int THIS = 45;
  public static final int ID = 50;
  public static final int DOT = 14;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 40;
  public static final int RCBR = 39;
  public static final int LB = 24;
  public static final int LAND = 23;
  public static final int EQUAL = 15;
  public static final int TRUE = 46;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int RB = 38;
  public static final int LOR = 30;
  public static final int NULL = 37;
  public static final int NUMBER = 49;
  public static final int MOD = 34;
  public static final int BREAK = 10;
  public static final int VOID = 47;
  public static final int GTE = 20;
  public static final int TIMES = 4;
  public static final int ELSE = 17;
  public static final int WHILE = 48;
  public static final int NEQUAL = 36;
  public static final int CLASS_ID = 52;
  public static final int EXTENDS = 16;
  public static final int STRING = 44;
  public static final int LNEG = 29;
  public static final int FALSE = 18;
  public static final int GT = 19;
  public static final int LENGTH = 27;
}

