package slp;
/* The following code was generated by JFlex 1.4.3 on 11/20/15 3:18 PM */

/***************************/
/* FILE NAME: LEX_FILE.lex */
/***************************/

/***************************/
/* AUTHOR: OREN ISH SHALOM */
/***************************/

/*************/
/* USER CODE */
/*************/
   
import java_cup.runtime.*;

/******************************/
/* DOLAR DOLAR - DON'T TOUCH! */
/******************************/
      

class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\12\1\2\1\0\1\12\1\1\22\0\1\13\1\54\1\4"+
    "\2\7\1\57\1\46\1\7\1\47\1\62\1\23\1\60\1\36\1\15"+
    "\1\41\1\22\1\14\11\16\1\7\1\63\1\56\1\24\1\45\2\7"+
    "\32\20\1\10\1\3\1\11\1\7\1\21\1\7\1\31\1\25\1\34"+
    "\1\43\1\30\1\44\1\51\1\52\1\37\1\17\1\33\1\27\1\17"+
    "\1\6\1\26\2\17\1\32\1\35\1\5\1\40\1\64\1\53\1\42"+
    "\2\17\1\50\1\55\1\61\1\7\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\2\3\1\4\1\5\1\6"+
    "\1\7\1\6\1\3\1\10\1\11\1\12\1\13\6\3"+
    "\1\14\1\3\1\15\1\3\1\16\1\1\1\17\1\20"+
    "\1\3\1\21\1\1\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\3\1\0\1\30\1\0\4\3\1\31\2\32"+
    "\1\33\12\3\1\34\1\3\1\35\1\36\1\3\1\37"+
    "\1\40\1\41\3\3\1\42\1\3\2\31\2\0\12\3"+
    "\1\43\3\3\1\44\1\45\1\46\3\3\1\47\10\3"+
    "\1\50\1\3\1\51\4\3\1\52\2\3\1\53\1\54"+
    "\1\3\1\55\1\3\1\56\1\3\1\57\1\60\1\61"+
    "\1\62\1\3\1\63";

  private static int [] zzUnpackAction() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\65\0\237\0\324\0\u0109\0\65"+
    "\0\65\0\65\0\u013e\0\u0173\0\u01a8\0\u01dd\0\u0212\0\u0247"+
    "\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba\0\65"+
    "\0\u03ef\0\65\0\u0424\0\u0459\0\u048e\0\65\0\65\0\u04c3"+
    "\0\u04f8\0\u052d\0\u0562\0\65\0\65\0\65\0\65\0\65"+
    "\0\u0597\0\u05cc\0\65\0\237\0\u0601\0\u0636\0\u066b\0\u06a0"+
    "\0\u06d5\0\u070a\0\65\0\65\0\u073f\0\u0774\0\u07a9\0\u07de"+
    "\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u01a8\0\u0951"+
    "\0\65\0\65\0\u0986\0\65\0\65\0\65\0\u09bb\0\u09f0"+
    "\0\u0a25\0\u01a8\0\u0a5a\0\u0a8f\0\65\0\u070a\0\u0ac4\0\u0af9"+
    "\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1"+
    "\0\u0cd6\0\u01a8\0\u0d0b\0\u0d40\0\u0d75\0\u01a8\0\u01a8\0\u01a8"+
    "\0\u0daa\0\u0ddf\0\u0e14\0\u01a8\0\u0e49\0\u0e7e\0\u0eb3\0\u0ee8"+
    "\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u01a8\0\u0ff1\0\u01a8\0\u1026"+
    "\0\u105b\0\u1090\0\u10c5\0\u01a8\0\u10fa\0\u112f\0\u01a8\0\u01a8"+
    "\0\u1164\0\u01a8\0\u1199\0\u01a8\0\u11ce\0\u01a8\0\u01a8\0\u01a8"+
    "\0\u01a8\0\u1203\0\u01a8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\7\1\2"+
    "\1\10\1\11\2\4\1\12\1\13\1\14\1\15\1\16"+
    "\1\2\1\17\1\20\1\21\1\22\1\15\1\23\1\24"+
    "\1\15\1\25\1\15\1\26\1\27\1\30\1\31\1\15"+
    "\1\32\2\15\1\33\1\34\1\35\1\36\1\37\2\15"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\67\0\1\4\65\0\1\52\1\53\5\54"+
    "\1\0\52\54\5\0\2\15\5\0\1\15\1\0\4\15"+
    "\3\0\5\15\1\55\3\15\1\0\2\15\1\0\3\15"+
    "\4\0\1\15\1\56\1\15\10\0\1\15\5\0\2\15"+
    "\5\0\1\15\1\0\4\15\3\0\3\15\1\57\5\15"+
    "\1\0\1\15\1\60\1\0\3\15\4\0\3\15\10\0"+
    "\1\15\16\0\1\14\62\0\1\14\1\0\1\14\53\0"+
    "\2\15\5\0\1\15\1\0\4\15\3\0\11\15\1\0"+
    "\2\15\1\0\3\15\4\0\3\15\10\0\1\15\5\0"+
    "\2\16\5\0\1\16\1\0\4\16\3\0\11\16\1\0"+
    "\2\16\1\0\3\16\4\0\3\16\10\0\1\16\22\0"+
    "\1\61\1\62\63\0\1\63\66\0\1\64\45\0\2\15"+
    "\5\0\1\15\1\0\4\15\3\0\1\15\1\65\3\15"+
    "\1\66\3\15\1\0\2\15\1\0\3\15\4\0\3\15"+
    "\10\0\1\15\5\0\2\15\5\0\1\15\1\0\4\15"+
    "\3\0\3\15\1\67\5\15\1\0\2\15\1\0\3\15"+
    "\4\0\3\15\10\0\1\15\5\0\2\15\5\0\1\15"+
    "\1\0\4\15\3\0\2\15\1\70\6\15\1\0\2\15"+
    "\1\0\1\71\2\15\4\0\3\15\10\0\1\15\5\0"+
    "\2\15\5\0\1\15\1\0\4\15\3\0\3\15\1\72"+
    "\5\15\1\0\2\15\1\0\3\15\4\0\3\15\10\0"+
    "\1\15\5\0\2\15\5\0\1\15\1\0\4\15\3\0"+
    "\1\15\1\73\1\74\6\15\1\0\2\15\1\0\3\15"+
    "\4\0\3\15\10\0\1\15\5\0\1\75\1\15\5\0"+
    "\1\15\1\0\4\15\3\0\11\15\1\0\2\15\1\0"+
    "\3\15\4\0\3\15\10\0\1\15\5\0\1\15\1\76"+
    "\5\0\1\15\1\0\4\15\3\0\11\15\1\0\2\15"+
    "\1\0\2\15\1\77\4\0\3\15\10\0\1\15\5\0"+
    "\2\15\5\0\1\15\1\0\4\15\3\0\4\15\1\100"+
    "\4\15\1\0\2\15\1\0\3\15\4\0\3\15\10\0"+
    "\1\15\24\0\1\101\106\0\1\102\23\0\2\15\5\0"+
    "\1\15\1\0\4\15\3\0\11\15\1\0\2\15\1\0"+
    "\3\15\4\0\1\15\1\103\1\15\10\0\1\15\24\0"+
    "\1\104\115\0\1\105\33\0\1\106\45\0\2\15\5\0"+
    "\1\15\1\0\4\15\3\0\1\15\1\107\7\15\1\0"+
    "\2\15\1\0\3\15\4\0\3\15\10\0\1\15\3\0"+
    "\4\54\63\0\2\15\5\0\1\15\1\0\4\15\3\0"+
    "\11\15\1\0\1\15\1\110\1\0\3\15\4\0\3\15"+
    "\10\0\1\15\5\0\2\15\5\0\1\15\1\0\4\15"+
    "\3\0\11\15\1\0\1\111\1\15\1\0\3\15\4\0"+
    "\3\15\10\0\1\15\5\0\2\15\5\0\1\15\1\0"+
    "\4\15\3\0\11\15\1\0\2\15\1\0\3\15\4\0"+
    "\2\15\1\112\10\0\1\15\5\0\2\15\5\0\1\15"+
    "\1\0\4\15\3\0\2\15\1\113\6\15\1\0\2\15"+
    "\1\0\3\15\4\0\3\15\10\0\1\15\1\61\1\114"+
    "\1\115\62\61\23\116\1\117\41\116\5\0\2\15\5\0"+
    "\1\15\1\0\4\15\3\0\1\15\1\120\7\15\1\0"+
    "\2\15\1\0\3\15\4\0\3\15\10\0\1\15\5\0"+
    "\2\15\5\0\1\15\1\0\4\15\3\0\3\15\1\121"+
    "\5\15\1\0\2\15\1\0\3\15\4\0\3\15\10\0"+
    "\1\15\5\0\1\15\1\122\5\0\1\15\1\0\4\15"+
    "\3\0\11\15\1\0\2\15\1\0\3\15\4\0\3\15"+
    "\10\0\1\15\5\0\2\15\5\0\1\15\1\0\4\15"+
    "\3\0\10\15\1\123\1\0\2\15\1\0\3\15\4\0"+
    "\3\15\10\0\1\15\5\0\1\124\1\15\5\0\1\15"+
    "\1\0\4\15\3\0\11\15\1\0\2\15\1\0\3\15"+
    "\4\0\3\15\10\0\1\15\5\0\1\125\1\15\5\0"+
    "\1\15\1\0\4\15\3\0\11\15\1\0\2\15\1\0"+
    "\3\15\4\0\3\15\10\0\1\15\5\0\1\15\1\126"+
    "\5\0\1\15\1\0\4\15\3\0\11\15\1\0\2\15"+
    "\1\0\3\15\4\0\3\15\10\0\1\15\5\0\2\15"+
    "\5\0\1\15\1\0\4\15\3\0\4\15\1\127\4\15"+
    "\1\0\2\15\1\0\3\15\4\0\3\15\10\0\1\15"+
    "\5\0\2\15\5\0\1\15\1\0\4\15\3\0\4\15"+
    "\1\130\1\131\3\15\1\0\2\15\1\0\3\15\4\0"+
    "\3\15\10\0\1\15\5\0\1\132\1\15\5\0\1\15"+
    "\1\0\4\15\3\0\11\15\1\0\2\15\1\0\3\15"+
    "\4\0\3\15\10\0\1\15\5\0\2\15\5\0\1\15"+
    "\1\0\4\15\3\0\2\15\1\133\6\15\1\0\2\15"+
    "\1\0\3\15\4\0\3\15\10\0\1\15\5\0\2\15"+
    "\5\0\1\15\1\0\4\15\3\0\11\15\1\0\1\134"+
    "\1\15\1\0\3\15\4\0\3\15\10\0\1\15\5\0"+
    "\2\15\5\0\1\15\1\0\4\15\3\0\11\15\1\0"+
    "\1\135\1\15\1\0\3\15\4\0\3\15\10\0\1\15"+
    "\5\0\2\15\5\0\1\15\1\0\4\15\3\0\3\15"+
    "\1\136\5\15\1\0\2\15\1\0\3\15\4\0\3\15"+
    "\10\0\1\15\5\0\2\15\5\0\1\15\1\0\4\15"+
    "\3\0\10\15\1\137\1\0\2\15\1\0\3\15\4\0"+
    "\3\15\10\0\1\15\5\0\2\15\5\0\1\15\1\0"+
    "\4\15\3\0\2\15\1\140\6\15\1\0\2\15\1\0"+
    "\3\15\4\0\3\15\10\0\1\15\2\0\1\115\62\0"+
    "\22\116\1\115\1\117\41\116\5\0\2\15\5\0\1\15"+
    "\1\0\4\15\3\0\2\15\1\141\6\15\1\0\2\15"+
    "\1\0\3\15\4\0\3\15\10\0\1\15\5\0\2\15"+
    "\5\0\1\15\1\0\4\15\3\0\4\15\1\142\4\15"+
    "\1\0\2\15\1\0\3\15\4\0\3\15\10\0\1\15"+
    "\5\0\2\15\5\0\1\15\1\0\4\15\3\0\11\15"+
    "\1\0\2\15\1\0\3\15\4\0\1\143\2\15\10\0"+
    "\1\15\5\0\2\15\5\0\1\15\1\0\4\15\3\0"+
    "\3\15\1\144\5\15\1\0\2\15\1\0\3\15\4\0"+
    "\3\15\10\0\1\15\5\0\2\15\5\0\1\15\1\0"+
    "\4\15\3\0\3\15\1\145\5\15\1\0\2\15\1\0"+
    "\3\15\4\0\3\15\10\0\1\15\5\0\2\15\5\0"+
    "\1\15\1\0\4\15\3\0\11\15\1\0\1\15\1\146"+
    "\1\0\3\15\4\0\3\15\10\0\1\15\5\0\1\147"+
    "\1\15\5\0\1\15\1\0\4\15\3\0\11\15\1\0"+
    "\2\15\1\0\3\15\4\0\3\15\10\0\1\15\5\0"+
    "\2\15\5\0\1\15\1\0\4\15\3\0\10\15\1\150"+
    "\1\0\2\15\1\0\3\15\4\0\3\15\10\0\1\15"+
    "\5\0\1\151\1\15\5\0\1\15\1\0\4\15\3\0"+
    "\11\15\1\0\2\15\1\0\3\15\4\0\3\15\10\0"+
    "\1\15\5\0\2\15\5\0\1\15\1\0\4\15\3\0"+
    "\11\15\1\0\1\152\1\15\1\0\3\15\4\0\3\15"+
    "\10\0\1\15\5\0\2\15\5\0\1\15\1\0\4\15"+
    "\3\0\10\15\1\153\1\0\2\15\1\0\3\15\4\0"+
    "\3\15\10\0\1\15\5\0\2\15\5\0\1\15\1\0"+
    "\4\15\3\0\2\15\1\154\6\15\1\0\2\15\1\0"+
    "\3\15\4\0\3\15\10\0\1\15\5\0\2\15\5\0"+
    "\1\15\1\0\4\15\3\0\11\15\1\0\2\15\1\0"+
    "\1\15\1\155\1\15\4\0\3\15\10\0\1\15\5\0"+
    "\2\15\5\0\1\15\1\0\4\15\3\0\3\15\1\156"+
    "\5\15\1\0\2\15\1\0\3\15\4\0\3\15\10\0"+
    "\1\15\5\0\2\15\5\0\1\15\1\0\4\15\3\0"+
    "\6\15\1\157\2\15\1\0\2\15\1\0\3\15\4\0"+
    "\3\15\10\0\1\15\5\0\1\160\1\15\5\0\1\15"+
    "\1\0\4\15\3\0\11\15\1\0\2\15\1\0\3\15"+
    "\4\0\3\15\10\0\1\15\5\0\1\15\1\161\5\0"+
    "\1\15\1\0\4\15\3\0\11\15\1\0\2\15\1\0"+
    "\3\15\4\0\3\15\10\0\1\15\5\0\2\15\5\0"+
    "\1\15\1\0\4\15\3\0\5\15\1\162\3\15\1\0"+
    "\2\15\1\0\3\15\4\0\3\15\10\0\1\15\5\0"+
    "\2\15\5\0\1\15\1\0\4\15\3\0\11\15\1\0"+
    "\1\163\1\15\1\0\3\15\4\0\3\15\10\0\1\15"+
    "\5\0\2\15\5\0\1\15\1\0\4\15\3\0\10\15"+
    "\1\164\1\0\2\15\1\0\3\15\4\0\3\15\10\0"+
    "\1\15\5\0\2\15\5\0\1\15\1\0\4\15\3\0"+
    "\11\15\1\0\1\165\1\15\1\0\3\15\4\0\3\15"+
    "\10\0\1\15\5\0\1\15\1\166\5\0\1\15\1\0"+
    "\4\15\3\0\11\15\1\0\2\15\1\0\3\15\4\0"+
    "\3\15\10\0\1\15\5\0\2\15\5\0\1\15\1\0"+
    "\4\15\3\0\3\15\1\167\5\15\1\0\2\15\1\0"+
    "\3\15\4\0\3\15\10\0\1\15\5\0\2\15\5\0"+
    "\1\15\1\0\4\15\3\0\3\15\1\170\5\15\1\0"+
    "\2\15\1\0\3\15\4\0\3\15\10\0\1\15\5\0"+
    "\2\15\5\0\1\15\1\0\4\15\3\0\4\15\1\171"+
    "\4\15\1\0\2\15\1\0\3\15\4\0\3\15\10\0"+
    "\1\15\5\0\2\15\5\0\1\15\1\0\4\15\3\0"+
    "\11\15\1\0\2\15\1\0\3\15\4\0\1\15\1\172"+
    "\1\15\10\0\1\15\5\0\2\15\5\0\1\15\1\0"+
    "\4\15\3\0\11\15\1\0\2\15\1\0\1\15\1\173"+
    "\1\15\4\0\3\15\10\0\1\15\5\0\1\15\1\174"+
    "\5\0\1\15\1\0\4\15\3\0\11\15\1\0\2\15"+
    "\1\0\3\15\4\0\3\15\10\0\1\15\5\0\1\15"+
    "\1\175\5\0\1\15\1\0\4\15\3\0\11\15\1\0"+
    "\2\15\1\0\3\15\4\0\3\15\10\0\1\15\5\0"+
    "\2\15\5\0\1\15\1\0\4\15\3\0\7\15\1\176"+
    "\1\15\1\0\2\15\1\0\3\15\4\0\3\15\10\0"+
    "\1\15\5\0\2\15\5\0\1\15\1\0\4\15\3\0"+
    "\11\15\1\0\2\15\1\0\3\15\4\0\1\177\2\15"+
    "\10\0\1\15\5\0\1\15\1\200\5\0\1\15\1\0"+
    "\4\15\3\0\11\15\1\0\2\15\1\0\3\15\4\0"+
    "\3\15\10\0\1\15\5\0\2\15\5\0\1\15\1\0"+
    "\4\15\3\0\10\15\1\201\1\0\2\15\1\0\3\15"+
    "\4\0\3\15\10\0\1\15\5\0\2\15\5\0\1\15"+
    "\1\0\4\15\3\0\11\15\1\0\1\15\1\202\1\0"+
    "\3\15\4\0\3\15\10\0\1\15\5\0\2\15\5\0"+
    "\1\15\1\0\4\15\3\0\3\15\1\203\5\15\1\0"+
    "\2\15\1\0\3\15\4\0\3\15\10\0\1\15";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4664];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\3\1\3\11\15\1\1\11"+
    "\1\1\1\11\3\1\2\11\4\1\5\11\1\1\1\0"+
    "\1\11\1\0\6\1\2\11\14\1\2\11\1\1\3\11"+
    "\6\1\1\11\2\0\64\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
private void printLineNumber(){
	System.out.println();
	System.out.print(yyline+1);
	System.out.print(": ");
}
    

/*************************************************************************

********/
    /* Create a new java_cup.runtime.Symbol with information about the 

current token */
    

/*************************************************************************

********/
    private Token symbol(int type)               {return new Token(type, 

yyline, yycolumn);}
    private Token symbol(int type, Object value) {return new Token(type, 

yyline, yycolumn, value);}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 25: 
          { /* skip */
          }
        case 52: break;
        case 35: 
          { printLineNumber(); System.out.print("INT"); return symbol(sym.INT);
          }
        case 53: break;
        case 13: 
          { printLineNumber(); System.out.print("DOT"); return symbol(sym.DOT);
          }
        case 54: break;
        case 44: 
          { printLineNumber(); System.out.print("WHILE"); return symbol(sym.WHILE);
          }
        case 55: break;
        case 3: 
          { printLineNumber();
						System.out.print("ID(");
						System.out.print(yytext());
						System.out.print(")");
						return symbol(sym.ID, new String(yytext()));
          }
        case 56: break;
        case 6: 
          { printLineNumber();
						System.out.print("INTEGER(");
						System.out.print(yytext());
						System.out.print(")");
						return symbol(sym.INT, new Integer(yytext()));
          }
        case 57: break;
        case 7: 
          { printLineNumber(); System.out.print("MINUS"); return symbol(sym.MINUS);
          }
        case 58: break;
        case 20: 
          { printLineNumber(); System.out.print("PLUS"); return symbol(sym.PLUS);
          }
        case 59: break;
        case 47: 
          { printLineNumber(); System.out.print("STATIC"); return symbol(sym.STATIC);
          }
        case 60: break;
        case 14: 
          { printLineNumber(); System.out.print("GT"); return symbol(sym.GT);
          }
        case 61: break;
        case 10: 
          { printLineNumber(); System.out.print("MULTIPLY"); return symbol(sym.MULTIPLY);
          }
        case 62: break;
        case 51: 
          { printLineNumber(); System.out.print("CONTINUE"); return symbol(sym.CONTINUE);
          }
        case 63: break;
        case 2: 
          { /* just skip what was found, do nothing */
          }
        case 64: break;
        case 4: 
          { printLineNumber(); System.out.print("LB"); return symbol(sym.LB);
          }
        case 65: break;
        case 1: 
          { throw new RuntimeException("Error: Invalid token: "+new String(yytext())+" at line " +Integer.toString(yyline+1));
          }
        case 66: break;
        case 19: 
          { printLineNumber(); System.out.print("MOD"); return symbol(sym.MOD);
          }
        case 67: break;
        case 29: 
          { printLineNumber(); System.out.print("GTE"); return symbol(sym.GTE);
          }
        case 68: break;
        case 33: 
          { printLineNumber(); System.out.print("LTE"); return symbol(sym.LTE);
          }
        case 69: break;
        case 27: 
          { printLineNumber(); System.out.print("EQUAL"); return symbol(sym.EQUAL);
          }
        case 70: break;
        case 28: 
          { printLineNumber(); System.out.print("IF"); return symbol(sym.IF);
          }
        case 71: break;
        case 36: 
          { printLineNumber(); System.out.print("TRUE"); return symbol(sym.TRUE);
          }
        case 72: break;
        case 17: 
          { printLineNumber(); System.out.print("LNEG"); return symbol(sym.LNEG);
          }
        case 73: break;
        case 15: 
          { printLineNumber(); System.out.print("LP"); return symbol(sym.LP);
          }
        case 74: break;
        case 46: 
          { printLineNumber(); System.out.print("RETURN"); return symbol(sym.RETURN);
          }
        case 75: break;
        case 12: 
          { printLineNumber(); System.out.print("COMMA"); return symbol(sym.COMMA);
          }
        case 76: break;
        case 32: 
          { printLineNumber(); System.out.print("LOR"); return symbol(sym.LOR);
          }
        case 77: break;
        case 21: 
          { printLineNumber(); System.out.print("RCBR"); return symbol(sym.RCBR);
          }
        case 78: break;
        case 38: 
          { printLineNumber(); System.out.print("NULL"); return symbol(sym.NULL);
          }
        case 79: break;
        case 23: 
          { printLineNumber(); System.out.print("SEMI"); return symbol(sym.SEMI);
          }
        case 80: break;
        case 45: 
          { printLineNumber(); System.out.print("LENGTH"); return symbol(sym.LENGTH);
          }
        case 81: break;
        case 5: 
          { printLineNumber(); System.out.print("RB"); return symbol(sym.RB);
          }
        case 82: break;
        case 43: 
          { printLineNumber(); System.out.print("FALSE"); return symbol(sym.FALSE);
          }
        case 83: break;
        case 40: 
          { printLineNumber(); System.out.print("VOID"); return symbol(sym.VOID);
          }
        case 84: break;
        case 49: 
          { printLineNumber(); System.out.print("BOOLEAN"); return symbol(sym.BOOLEAN);
          }
        case 85: break;
        case 39: 
          { printLineNumber(); System.out.print("ELSE"); return symbol(sym.ELSE);
          }
        case 86: break;
        case 37: 
          { printLineNumber(); System.out.print("THIS"); return symbol(sym.THIS);
          }
        case 87: break;
        case 11: 
          { printLineNumber(); System.out.print("ASSIGN"); return symbol(sym.ASSIGN);
          }
        case 88: break;
        case 30: 
          { printLineNumber(); System.out.print("LAND"); return symbol(sym.LAND);
          }
        case 89: break;
        case 31: 
          { printLineNumber(); System.out.print("NEQUAL"); return symbol(sym.NEQUAL);
          }
        case 90: break;
        case 9: 
          { printLineNumber(); System.out.print("DIVIDE");    return symbol(sym.DIVIDE);
          }
        case 91: break;
        case 48: 
          { printLineNumber(); System.out.print("STRING"); return symbol(sym.STRING);
          }
        case 92: break;
        case 16: 
          { printLineNumber(); System.out.print("LCBR"); return symbol(sym.LCBR);
          }
        case 93: break;
        case 50: 
          { printLineNumber(); System.out.print("EXTENDS"); return symbol(sym.EXTENDS);
          }
        case 94: break;
        case 26: 
          { throw new RuntimeException("Error: unclosed comment at line "+Integer.toString(yyline+1));
          }
        case 95: break;
        case 22: 
          { printLineNumber(); System.out.print("RP"); return symbol(sym.RP);
          }
        case 96: break;
        case 24: 
          { printLineNumber();
						System.out.print("QUOTE(");
						System.out.print(yytext());
						System.out.print(")");
						return symbol(sym.QUOTE, new String(yytext()));
          }
        case 97: break;
        case 34: 
          { printLineNumber(); System.out.print("NEW"); return symbol(sym.NEW);
          }
        case 98: break;
        case 18: 
          { printLineNumber(); System.out.print("LT"); return symbol(sym.LT);
          }
        case 99: break;
        case 41: 
          { printLineNumber(); System.out.print("BREAK"); return symbol(sym.BREAK);
          }
        case 100: break;
        case 8: 
          { printLineNumber();
						System.out.print("CLASS_ID(");
						System.out.print(yytext());
						System.out.print(")");
						return symbol(sym.CLASS_ID, new String(yytext()));
          }
        case 101: break;
        case 42: 
          { printLineNumber(); System.out.print("CLASS"); return symbol(sym.CLASS);
          }
        case 102: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
