
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 22 08:04:42 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LCBR = 49;
  public static final int LTE = 30;
  public static final int MULT = 4;
  public static final int GE = 12;
  public static final int UMINUS = 19;
  public static final int INTEGER = 25;
  public static final int LPAREN = 6;
  public static final int SEMI = 8;
  public static final int CONTINUE = 26;
  public static final int INT = 20;
  public static final int MINUS = 3;
  public static final int STATIC = 23;
  public static final int RPAREN = 7;
  public static final int LT = 11;
  public static final int LP = 35;
  public static final int COMMA = 37;
  public static final int CLASS = 55;
  public static final int RP = 51;
  public static final int PLUS = 2;
  public static final int MULTIPLY = 24;
  public static final int QUOTE = 52;
  public static final int ASSIGN = 9;
  public static final int IF = 32;
  public static final int THIS = 46;
  public static final int DOT = 21;
  public static final int ID = 18;
  public static final int LE = 13;
  public static final int BOOLEAN = 44;
  public static final int EOF = 0;
  public static final int RCBR = 38;
  public static final int RETURN = 36;
  public static final int LB = 27;
  public static final int LAND = 14;
  public static final int EQUAL = 31;
  public static final int TRUE = 33;
  public static final int NEW = 53;
  public static final int error = 1;
  public static final int RB = 41;
  public static final int LOR = 15;
  public static final int NULL = 39;
  public static final int NUMBER = 16;
  public static final int MOD = 28;
  public static final int BREAK = 54;
  public static final int VOID = 43;
  public static final int GTE = 29;
  public static final int ELSE = 45;
  public static final int WHILE = 22;
  public static final int NEQUAL = 47;
  public static final int CLASS_ID = 17;
  public static final int EXTENDS = 50;
  public static final int STRING = 48;
  public static final int LNEG = 34;
  public static final int FALSE = 42;
  public static final int GT = 10;
  public static final int LENGTH = 40;
}

