
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 27 17:57:09 IST 2015
//----------------------------------------------------

package slp;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 5;
  public static final int LCBR = 43;
  public static final int LTE = 24;
  public static final int INTEGER = 19;
  public static final int SEMI = 6;
  public static final int CONTINUE = 20;
  public static final int INT = 15;
  public static final int MINUS = 3;
  public static final int STATIC = 18;
  public static final int LT = 9;
  public static final int LP = 29;
  public static final int COMMA = 31;
  public static final int CLASS = 48;
  public static final int RP = 45;
  public static final int PLUS = 2;
  public static final int MULTIPLY = 4;
  public static final int ASSIGN = 7;
  public static final int QUOTE = 14;
  public static final int IF = 26;
  public static final int THIS = 40;
  public static final int DOT = 16;
  public static final int ID = 13;
  public static final int BOOLEAN = 38;
  public static final int EOF = 0;
  public static final int RCBR = 32;
  public static final int LB = 21;
  public static final int LAND = 10;
  public static final int RETURN = 30;
  public static final int EQUAL = 25;
  public static final int TRUE = 27;
  public static final int NEW = 46;
  public static final int error = 1;
  public static final int RB = 35;
  public static final int LOR = 11;
  public static final int NULL = 33;
  public static final int MOD = 22;
  public static final int BREAK = 47;
  public static final int VOID = 37;
  public static final int GTE = 23;
  public static final int ELSE = 39;
  public static final int WHILE = 17;
  public static final int NEQUAL = 41;
  public static final int CLASS_ID = 12;
  public static final int EXTENDS = 44;
  public static final int STRING = 42;
  public static final int LNEG = 28;
  public static final int FALSE = 36;
  public static final int GT = 8;
  public static final int LENGTH = 34;
}

